// Betapp design system — calm recovery palette (no casino red/gold).
export const palette = {
  primary: '#1E3A5F',
  primaryDark: '#152A45',
  // Neutral soft fill — keep brand via icons/text, not a blue wash behind content.
  primarySoft: '#E8ECF1',
  secondary: '#2A9D8F',
  secondaryDark: '#1F7F73',
  secondarySoft: '#DDF3F0',
  background: '#F4F6F9',
  surface: '#FFFFFF',
  surfaceMuted: '#EEF2F6',
  text: '#2B2D42',
  textSecondary: '#6B7280',
  textMuted: '#9CA3AF',
  border: '#E3E7EE',
  warning: '#E9C46A',
  warningSoft: '#FBF4DF',
  // Darker amber for small text on light backgrounds (WCAG AA).
  warningText: '#7A6210',
  success: '#4CAF87',
  successSoft: '#E4F5ED',
  white: '#FFFFFF',
  black: '#0F1419',
};

export const lightColors = {
  background: palette.background,
  surface: palette.surface,
  surfaceMuted: palette.surfaceMuted,
  primary: palette.primary,
  primaryMuted: palette.primarySoft,
  secondary: palette.secondary,
  secondaryMuted: palette.secondarySoft,
  // Streaks / links / progress accents use calm teal.
  accent: palette.secondary,
  accentMuted: palette.secondarySoft,
  text: palette.text,
  textSecondary: palette.textSecondary,
  textInverse: palette.white,
  border: palette.border,
  success: palette.success,
  successMuted: palette.successSoft,
  // Alerts / restrictions use muted amber — never bright red.
  warning: palette.warning,
  warningMuted: palette.warningSoft,
  danger: palette.warningText,
  dangerMuted: palette.warningSoft,
  overlay: 'rgba(43, 45, 66, 0.45)',
  gradient: [palette.primary, palette.secondary],
  splashGradient: [palette.primaryDark, palette.primary, palette.secondary],
  // Soft professional canvas (navy mist → white → teal mist).
  canvasGradient: ['#E9EEF5', '#F7F9FC', '#EAF4F2'],
  statusBar: 'dark',
};

export const darkColors = {
  // Neutral charcoal — avoid navy/indigo so dark mode does not read as "blue screens".
  background: '#14161A',
  surface: '#1C1F24',
  surfaceMuted: '#262A31',
  primary: '#8FA9C7',
  primaryMuted: '#2A3038',
  secondary: '#4DB8A9',
  secondaryMuted: '#1D3F3A',
  accent: '#4DB8A9',
  accentMuted: '#1D3F3A',
  text: '#F3F5F8',
  textSecondary: '#A7B0BD',
  textInverse: '#14161A',
  border: '#333842',
  success: '#6BC49C',
  successMuted: '#1E3A30',
  warning: palette.warning,
  warningMuted: '#3D3520',
  danger: '#E9C46A',
  dangerMuted: '#3D3520',
  overlay: 'rgba(0, 0, 0, 0.55)',
  gradient: [palette.primary, palette.secondary],
  splashGradient: ['#14161A', palette.primaryDark, '#1D3F3A'],
  canvasGradient: ['#1A1F27', '#14161A', '#15221A'],
  statusBar: 'light',
};
